//15-DADA UNA COMPRA DE 30 PCPARA UNA EMPRESA Y SABIENDO QUECADA UNA CUESTA 11500 PESOS.
//SÉ QUE EL PROVEEDOR ME HACE UN 20% DE DESCUENTO.
//SÉ QUE EL ENVÍO ME COBRA UN 5% DEL TOTAL.
//SÉ QUE EL SEGURO DE TRASLADO ES 12% DEL TOTAL EL CUAL SE DEVUELVEN SI LOS EQUIPOS LLEGAN BIEN.
//OBTENER EL PRECIO SIN DESCUENTOS. EL PRECIO CON TODOS LOS DESCUENTOS SI TODAS LAS PC LLEGAN BIEN. 
//EL PRECIO CON TODOS LOS DESCUENTOS SI LAS PC LLEGAN MAL. SOLAMENTE EL PRECIO DEL DESCUENTO, SOLAMENTE EL PRECIO DEL ENVÍO.

 
